### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [abiscuola/zc-portable#1]
Hello!

Could you please add information about license — is it allowed to copy, change and use code in any purpose?
It would be great to see any popular open source license.

**Comment by abiscuola** [comment]
Hi Alexey!

On Sun, 29 Mar 2020 09:46:04 -0700
Alexey Vazhnov <notifications@github.com> wrote:

> Hello!
> 
> Could you please add information about license — is it allowed to copy, change and use code in any purpose?
> It would be great to see any popular open source license.
> 

I just noticed Github removed it :)

Don't worry, the code is licensed under the ISC license (essentially, a BSD license).
You can do whatever you want with it and, in general, the license is at the top of every
source file.

Anyway, I'll see if I can add a LICENSE file then.

Thanks for pointing it out

Andrea.

**Comment by abiscuola** [comment]
Hi again!

I added a small section about the license informations in the README file. There
is no need for a dedicated file, being the ISC license on a per-file basis.

Thanks again for your contribution.

Regards

Andrea

**Comment by abiscuola** [comment]
Fixed with e8df375c807c19e036fe
